const CategoriasTypes = {
  BUSCA_CATEGORIAS_START: 'BUSCA_CATEGORIAS_START',
  BUSCA_CATEGORIAS_SUCCESS: 'BUSCA_CATEGORIAS_SUCCESS',
  BUSCA_CATEGORIAS_FAILURE: 'BUSCA_CATEGORIAS_FAILURE',
  ADD_CATEGORIA: 'ADD_CATEGORIA',
};

export default CategoriasTypes;
