const LendoTypes = {
  BUSCA_LENDO_START: 'BUSCA_LENDO_START',
  BUSCA_LENDO_SUCCESS: 'BUSCA_LENDO_SUCCESS',
  BUSCA_LENDO_ERROR: 'BUSCA_LENDO_ERROR',
  ADD_LENDO_LIVRO: 'ADD_LENDO_LIVRO',
  NOVO_LENDO_LIVRO: 'NOVO_LENDO_LIVRO',
  REMOVER_LENDO_LIVRO: 'REMOVER_LENDO_LIVRO',
  ALTERAR_CATEGORIA_LENDO: 'ALTERAR_CATEGORIA_LENDO',
};

export default LendoTypes;
