const LendoTypes = {
  BUSCA_LENDO_START: 'BUSCA_LENDO_START',
  BUSCA_LENDO_SUCCESS: 'BUSCA_LENDO_SUCCESS',
  BUSCA_LENDO_ERROR: 'BUSCA_LENDO_ERROR',
  ADD_LENDO_LIVRO_START: 'ADD_LENDO_LIVRO_START',
  ADD_LENDO_LIVRO_SUCCESS: 'ADD_LENDO_LIVRO_SUCCESS',
  ADD_LENDO_LIVRO_FAILURE: 'ADD_LENDO_LIVRO_FAILURE',
  REMOVER_LENDO_LIVRO: 'REMOVER_LENDO_LIVRO',
};

export default LendoTypes;
