const ConcluidoTypes = {
  BUSCA_CONCLUIDO_START: 'BUSCA_CONCLUIDO_START',
  BUSCA_CONCLUIDO_SUCCESS: 'BUSCA_CONCLUIDO_SUCCESS',
  BUSCA_CONCLUIDO_ERROR: 'BUSCA_CONCLUIDO_ERROR',
  ADD_LIVRO_CONCLUIDO_START: 'ADD_LIVRO_CONCLUIDO_START',
  ADD_LIVRO_CONCLUIDO_SUCCESS: 'ADD_LIVRO_CONCLUIDO_SUCCESS',
  ADD_LIVRO_CONCLUIDO_FAILURE: 'ADD_LIVRO_CONCLUIDO_FAILURE',
  REMOVER_LIVRO_CONCLUIDO: 'REMOVER_LIVRO_CONCLUIDO',
};

export default ConcluidoTypes;
