const ConcluidoTypes = {
  BUSCA_CONCLUIDO_START: 'BUSCA_CONCLUIDO_START',
  BUSCA_CONCLUIDO_SUCCESS: 'BUSCA_CONCLUIDO_SUCCESS',
  BUSCA_CONCLUIDO_ERROR: 'BUSCA_CONCLUIDO_ERROR',
  ADD_LIVRO_CONCLUIDO: 'ADD_LIVRO_CONCLUIDO',
  NOVO_LIVRO_CONCLUIDO: 'NOVO_LIVRO_CONCLUIDO',
  REMOVER_LIVRO_CONCLUIDO: 'REMOVER_LIVRO_CONCLUIDO',
  ALTERAR_CATEGORIA_LIVRO_CONCLUIDO: 'ALTERAR_CATEGORIA_LIVRO_CONCLUIDO',
};

export default ConcluidoTypes;
