const ConcluidoTypes = {
  BUSCA_CONCLUIDO_START: 'BUSCA_CONCLUIDO_START',
  BUSCA_CONCLUIDO_SUCCESS: 'BUSCA_CONCLUIDO_SUCCESS',
  BUSCA_CONCLUIDO_ERROR: 'BUSCA_CONCLUIDO_ERROR',
};

export default ConcluidoTypes;
