const ListaDesejoTypes = {
  BUSCA_LISTA_DESEJO_START: 'BUSCA_LISTA_DESEJO_START',
  BUSCA_LISTA_DESEJO_SUCCESS: 'BUSCA_LISTA_DESEJO_SUCCESS',
  BUSCA_LISTA_DESEJO_ERROR: 'BUSCA_LISTA_DESEJO_ERROR',
  ADD_LIVRO_LISTA_DESEJO_START: 'ADD_LIVRO_LISTA_DESEJO_START',
  ADD_LIVRO_LISTA_DESEJO_SUCCESS: 'ADD_LIVRO_LISTA_DESEJO_SUCCESS',
  ADD_LIVRO_LISTA_DESEJO_FAILURE: 'ADD_LIVRO_LISTA_DESEJO_FAILURE',
  REMOVER_LIVRO_LISTA_DESEJO: 'REMOVER_LIVRO_LISTA_DESEJO',
};

export default ListaDesejoTypes;
