const ListaDesejoTypes = {
  BUSCA_LISTA_DESEJO_START: 'BUSCA_LISTA_DESEJO_START',
  BUSCA_LISTA_DESEJO_SUCCESS: 'BUSCA_LISTA_DESEJO_SUCCESS',
  BUSCA_LISTA_DESEJO_ERROR: 'BUSCA_LISTA_DESEJO_ERROR',
  ADD_LIVRO_LISTA_DESEJO: 'ADD_LIVRO_LISTA_DESEJO',
  NOVO_LIVRO_LISTA_DESEJO: 'NOVO_LIVRO_LISTA_DESEJO',
  REMOVER_LIVRO_LISTA_DESEJO: 'REMOVER_LIVRO_LISTA_DESEJO',
  ALTERAR_CATEGORIA_LIVRO_LISTA_DESEJO: 'ALTERAR_CATEGORIA_LIVRO_LISTA_DESEJO',
};

export default ListaDesejoTypes;
