const ListaDesejoTypes = {
  BUSCA_LISTA_DESEJO_START: 'BUSCA_LISTA_DESEJO_START',
  BUSCA_LISTA_DESEJO_SUCCESS: 'BUSCA_LISTA_DESEJO_SUCCESS',
  BUSCA_LISTA_DESEJO_ERROR: 'BUSCA_LISTA_DESEJO_ERROR',
};

export default ListaDesejoTypes;
